### ISSUE TITLE
Notifications not loading

### ISSUE THREAD

**Issue by udaykumaruking** [TheAlphamerc/flutter-GitConnect#3]
![image](https://user-images.githubusercontent.com/32547287/96832719-d64f4c80-145c-11eb-801f-652a7d9f5f2d.png)

Hey I have used your app and I loved it but I found an issue with your application in Android Operating System. I hope you can understand the problem when you see the image.

**Comment by TheAlphamerc** [comment]
Did you try with restarting the app?

**Comment by udaykumaruking** [comment]
@TheAlphamerc Yes, I tried it.

**Comment by TheAlphamerc** [comment]
Did you download the app from the play store ?

**Comment by udaykumaruking** [comment]
yes, @TheAlphamerc I downloaded it from the play store.

**Comment by TheAlphamerc** [comment]
@udaykumaruking I have checked this and didn't get this error a single time. Can you share a video? It will be helpful to understand.

**Comment by udaykumaruking** [comment]
Yeah, sure I will do it.
