### ISSUE TITLE
App title is not correct.

### ISSUE THREAD

**Issue by udaykumaruking** [TheAlphamerc/flutter-GitConnect#4]
![image](https://user-images.githubusercontent.com/32547287/96833077-72795380-145d-11eb-9952-d7795ca87dc4.png)
![image](https://user-images.githubusercontent.com/32547287/96833086-75744400-145d-11eb-8ecc-812d46125d34.png)
![image](https://user-images.githubusercontent.com/32547287/96833092-786f3480-145d-11eb-8b67-7a741b19bd1f.png)

If you see the above three images the title of the app is changing based on the screen we present. I have opened the WhatsApp application it's showing the same i.e., **Whatsapp** for all of the pages irrespective of chats, status, calls tab.

**Comment by TheAlphamerc** [comment]
Hi @udaykumaruking , Here the title is displaying the name of the current screen name which is active in app.

**Comment by udaykumaruking** [comment]
Yes, @TheAlphamerc I understand it but normal applications don't perform in that way right. I think you need to change it.

**Comment by TheAlphamerc** [comment]
Ok, Will fix it.

**Comment by udaykumaruking** [comment]
Yes, @TheAlphamerc I loved your application.
