### ISSUE TITLE
Text not rendering properly

### ISSUE THREAD

**Issue by udaykumaruking** [TheAlphamerc/flutter-GitConnect#5]
**PS: Sorry, don't feel bad that I am submitting more issues I want to help you that is the reason I am submitting the issues.**

![image](https://user-images.githubusercontent.com/32547287/96833742-8bcecf80-145e-11eb-8657-56d9b62ec080.png)

If you can see in the image the text is not rendering properly probably its issue with responsiveness. I hope you need to increase the height of the container on the profile screen.

_I would like to suggest one feature in the contribution section instead of sharp edges for the square you can make it rounded edges._

**Comment by TheAlphamerc** [comment]
Thanks @udaykumaruking for letting me know. I will fix this in next release.

**Comment by udaykumaruking** [comment]
@TheAlphamerc Even I faced this issue when I used the google fonts package from the pub.dev website.

Basically, that problem will arise due to SKIA rendering, `flutter run -d chrome --debug --dart-define=FLUTTER_WEB_USE_SKIA=true` use this command then the text will render perfectly.

**Comment by udaykumaruking** [comment]
For further information regarding the above comment see the following [issue](https://github.com/flutter/flutter/issues/67327) from Flutter.

**Comment by TheAlphamerc** [comment]
@udaykumaruking this issues is not related to skia. I think a little padding or margin can fix it.

**Comment by udaykumaruking** [comment]
I think there is also a problem with text rendering I feel the text is getting cropped at the bottom.
