### ISSUE TITLE
Some file missing i think

### ISSUE THREAD

**Issue by aTeamSolace** [TheAlphamerc/flutter-GitConnect#7]
import 'package:flutter_github_connect/helper/git_config.dart';  

This file is not found

**Comment by TheAlphamerc** [comment]
@aTeamSolace There is a file in helper folder names `git_config.dart.template`. Rename this file to `git_config.dart`.
Create OAuth app from GitHub and get client id and secret code from there and add those to this file.
Check [here](https://docs.github.com/en/free-pro-team@latest/developers/apps/creating-an-oauth-app) about how to create OAuth app for GitHub.

<img width="935" alt="Screenshot 2020-10-23 at 9 54 31 AM" src="https://user-images.githubusercontent.com/37103237/96956552-073f8800-1516-11eb-95c5-142e711fb085.png">

**Comment by aTeamSolace** [comment]
@TheAlphamerc Thank you sir.
