### ISSUE TITLE
Undefined name 'GitConfig'.

### ISSUE THREAD

**Issue by bahaafathi** [TheAlphamerc/flutter-GitConnect#9]
this file is missing؟

**Comment by TheAlphamerc** [comment]
Hi @bahaafathi. This file contain Github Client Id and Client Secret key so it isn't checked in git. However I've added a template file in code named `GitConfig.template.dart`.  Rename this file to `GitConfig.dart` and add required keys in it.
For detail info check this [thread](https://github.com/TheAlphamerc/flutter-GitConnect/issues/7#issuecomment-714903517)
